### ISSUE TITLE
No module named 'MinkowskiEngine'

### ISSUE THREAD

**Issue by hj2532006916** [JonasSchult/Mask3D#105]
![image](https://github.com/JonasSchult/Mask3D/assets/133661066/516406d7-af9e-4ce2-9e34-62b7a4a7ac9a)
how to solve this problem? @JonasSchult

**Comment by JonasSchult** [comment]
Hi!

Did you follow all installation steps in the readme? It seems like you didnt install the MinkowskiEngine.

Best,
Jonas

**Comment by hj2532006916** [comment]
Thank you for your reply. My Cuda version is different from yours, but I installed it according to the instructions. I don't know if it will have an impact

**Comment by Vinit2244** [comment]
Hey,
I faced a similar issue while trying to run the basic visualisation code of https://github.com/cvg/Mask3D. Just adding the absolute path of `MinkowskiEngine` folder to my python search paths solved the issue for me. You can check the list of your python search paths using the following command:
```shell
python3 -c "import sys; print(sys.path)"
```

If path to MinkowskiEngine folder is not there you can manually add the path as follows:
```shell
export PYTHONPATH=<absolute_path_to_MinkowskiEngine_folder>:$PYTHONPATH
```

PS: My PC's specs: Ubuntu 22.04.5 LTS (jammy)

---
Error I faced was this:
```text
Traceback (most recent call last):
  File "/home/wstation/Desktop/vinit/Mask3D/visualise.py", line 2, in <module>
    from mask3d import get_model, load_mesh, prepare_data, map_output_to_pointcloud, save_colorized_mesh 
  File "/home/wstation/Desktop/vinit/Mask3D/mask3d/__init__.py", line 4, in <module>
    from mask3d.models.mask3d import Mask3D
  File "/home/wstation/Desktop/vinit/Mask3D/mask3d/models/__init__.py", line 1, in <module>
    import mask3d.models.resunet as resunet
  File "/home/wstation/Desktop/vinit/Mask3D/mask3d/models/resunet.py", line 2, in <module>
    import MinkowskiEngine as ME
ModuleNotFoundError: No module named 'MinkowskiEngine'
```
