### ISSUE TITLE
pycharm debug error

### ISSUE THREAD

**Issue by TalonX1** [JonasSchult/Mask3D#114]
when I try to debug to see the data stream in train, I add breakpoint to res16unut forward, for example "out = self.conv0p1s1(x)", I always get the error,but I can successfully run it without debugging.I hope you can help me. Thank you very much

```
  | Name      | Type         | Params
-------------------------------------------
0 | model     | Mask3D       | 39.6 M
1 | criterion | SetCriterion | 0     
-------------------------------------------
39.6 M    Trainable params
0         Non-trainable params
39.6 M    Total params
158.466   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:219: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
pydev debugger: warning: trying to add breakpoint to file that does not exist: /data2/qhb/mask3d/Mask3D-main_20230621/c:/users/timeassassin/appdata/local/jetbrains/pycharm2022.1/remote_sources/1527222065/2077036789/fire/core.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /data2/qhb/mask3d/Mask3D-main_20230621/c:/users/timeassassin/appdata/local/jetbrains/pycharm2022.1/remote_sources/1527222065/2077036789/fire/core.py (will have no effect)
Sanity Checking DataLoader 0:   0%|                       | 0/2 [00:00<?, ?it/s]CUDA error: an illegal memory access was encountered
Traceback (most recent call last):
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/data2/qhb/mask3d/Mask3D-main_20230621/trainer/trainer.py", line 160, in validation_step
    return self.eval_step(batch, batch_idx)
  File "/data2/qhb/mask3d/Mask3D-main_20230621/trainer/trainer.py", line 357, in eval_step
    raise run_err
  File "/data2/qhb/mask3d/Mask3D-main_20230621/trainer/trainer.py", line 348, in eval_step
    output = self.forward(data,
  File "/data2/qhb/mask3d/Mask3D-main_20230621/trainer/trainer.py", line 92, in forward
    x = self.model(x, point2segment, raw_coordinates=raw_coordinates,         # 输入x为（坐标和特征）稀疏化后的向量，shape同样为n*3,n为点数
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/qhb/mask3d/Mask3D-main_20230621/models/mask3d.py", line 243, in forward
    pcd_features, aux = self.backbone(x)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/qhb/mask3d/Mask3D-main_20230621/models/res16unet.py", line 228, in forward
    out = self.bn0(out)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/MinkowskiEngine-0.5.4-py3.10-linux-x86_64.egg/MinkowskiEngine/MinkowskiNormalization.py", line 75, in forward
    output = self.bn(input.F)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/functional.py", line 2438, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA error: an illegal memory access was encountered
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "/data2/qhb/mask3d/Mask3D-main_20230621/main_instance_segmentation.py", line 116, in main
    train(cfg)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/data2/qhb/mask3d/Mask3D-main_20230621/main_instance_segmentation.py", line 97, in train
    runner.fit(model)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 664, in _call_and_handle_interrupt
    self._teardown()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1231, in _teardown
    self.strategy.teardown()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 476, in teardown
    self.lightning_module.cpu()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 141, in cpu
python-BaseException
    return super().cpu()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 738, in cpu
    return self._apply(lambda t: t.cpu())
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 738, in <lambda>
    return self._apply(lambda t: t.cpu())
RuntimeError: CUDA error: an illegal memory access was encountered
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 267, in run_and_report
    print_exception(etype=None, value=ex, tb=final_tb)  # type: ignore
TypeError: print_exception() got an unexpected keyword argument 'etype'

```

**Comment by SnowCastle123** [comment]
你好，我也碰到同样的问题，一样是在debug的时候不能通过，但是直接run可以通过，我的报错跟你一样，我观察到张量在进入第一个卷积时就变成unable to get 的状态，最后报错指向softmax函数，请问你是怎么解决的
File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/qjc21/powerline_V5/trainer/trainer.py", line 161, in validation_step
    return self.eval_step(batch, batch_idx)
  File "/home/qjc21/powerline_V5/trainer/trainer.py", line 400, in eval_step
    losses = self.criterion(output, target,
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qjc21/powerline_V5/models/criterion.py", line 259, in forward
    indices = self.matcher(outputs_without_aux, targets, mask_type)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/qjc21/powerline_V5/models/matcher.py", line 190, in forward
    return self.memory_efficient_forward(outputs, targets, mask_type)
  File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/qjc21/powerline_V5/models/matcher.py", line 105, in memory_efficient_forward
    out_prob = outputs["pred_logits"][b].softmax(-1)  # [num_queries, num_classes]
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by TalonX1** [comment]
> 你好，我也碰到同样的问题，一样是在debug的时候不能通过，但是直接run可以通过，我的报错跟你一样，我观察到张量在进入第一个卷积时就变成unable to get 的状态，最后报错指向softmax函数，请问你是怎么解决的 File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt return trainer_fn(*args, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl results = self._run(model, ckpt_path=self.ckpt_path) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run results = self._run_stage() File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage return self._run_train() File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train self._run_sanity_check() File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check val_loop.run() File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run self.advance(*args, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run self.advance(*args, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance output = self._evaluation_step(**kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step output = self.trainer._call_strategy_hook(hook_name, *kwargs.values()) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook output = fn(*args, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step return self.model.validation_step(*args, **kwargs) File "/home/qjc21/powerline_V5/trainer/trainer.py", line 161, in validation_step return self.eval_step(batch, batch_idx) File "/home/qjc21/powerline_V5/trainer/trainer.py", line 400, in eval_step losses = self.criterion(output, target, File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/qjc21/powerline_V5/models/criterion.py", line 259, in forward indices = self.matcher(outputs_without_aux, targets, mask_type) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/home/qjc21/powerline_V5/models/matcher.py", line 190, in forward return self.memory_efficient_forward(outputs, targets, mask_type) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/home/qjc21/powerline_V5/models/matcher.py", line 105, in memory_efficient_forward out_prob = outputs["pred_logits"][b].softmax(-1) # [num_queries, num_classes] RuntimeError: CUDA error: an illegal memory access was encountered

You can try add "CUDA_VISIBLE_DEVICES=xxx" to environment variables in debug, and set "gpus=0" in config file. Or you can use id=0 gpu for debug directly without adove settings.

**Comment by SnowCastle123** [comment]
> > 你好，我也碰到同样的问题，一样是在debug的时候不能通过，但是直接run可以通过，我的报错跟你一样，我观察到张量在进入第一个卷积时就变成unable to get 的状态，最后报错指向softmax函数，请问你是怎么解决的 File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt return trainer_fn(*args, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl results = self._run(model, ckpt_path=self.ckpt_path) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run results = self._run_stage() File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage return self._run_train() File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train self._run_sanity_check() File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check val_loop.run() File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run self.advance(*args, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run self.advance(*args, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance output = self._evaluation_step(**kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step output = self.trainer._call_strategy_hook(hook_name, *kwargs.values()) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook output = fn(*args, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step return self.model.validation_step(*args, **kwargs) File "/home/qjc21/powerline_V5/trainer/trainer.py", line 161, in validation_step return self.eval_step(batch, batch_idx) File "/home/qjc21/powerline_V5/trainer/trainer.py", line 400, in eval_step losses = self.criterion(output, target, File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/qjc21/powerline_V5/models/criterion.py", line 259, in forward indices = self.matcher(outputs_without_aux, targets, mask_type) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/home/qjc21/powerline_V5/models/matcher.py", line 190, in forward return self.memory_efficient_forward(outputs, targets, mask_type) File "/home/qjc21/.conda/envs/mask3d/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/home/qjc21/powerline_V5/models/matcher.py", line 105, in memory_efficient_forward out_prob = outputs["pred_logits"][b].softmax(-1) # [num_queries, num_classes] RuntimeError: CUDA error: an illegal memory access was encountered
> 
> You can try add "CUDA_VISIBLE_DEVICES=xxx" to environment variables in debug, and set "gpus:[0]" in config file. Or you can use id=0 gpu for debug directly without adove settings.

非常感谢您的回复，我已经成功解决这个问题，如果需要debug，则必须使用GPU0（在单机多卡上），如果需要run，则可以指定任何一张卡，并不影响结果。我认为这可能是lighting的bug。
