### ISSUE TITLE
CUDAAccelerator error while tranning

### ISSUE THREAD

**Issue by narges-tk** [JonasSchult/Mask3D#164]
/home/ntakhtke/miniconda3/envs/mask3d_n2/lib/python3.10/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 304: OS call failed or operation not supported on this OS (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/ntakhtke/DL_models/mask3d_2/Mask3D/main_instance_segmentation.py", line 108, in main
    train(cfg)
  File "/home/ntakhtke/miniconda3/envs/mask3d_n2/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/ntakhtke/DL_models/mask3d_2/Mask3D/main_instance_segmentation.py", line 77, in train
    runner = Trainer(
  File "/home/ntakhtke/miniconda3/envs/mask3d_n2/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/ntakhtke/miniconda3/envs/mask3d_n2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 433, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/home/ntakhtke/miniconda3/envs/mask3d_n2/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 213, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/home/ntakhtke/miniconda3/envs/mask3d_n2/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 530, in _set_parallel_devices_and_init_accelerator
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: CUDAAccelerator can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].

**Comment by KatherineJames** [comment]
@narges-tk did you solve this issue?
