### ISSUE TITLE
MinkowskiEngine Undefined Symbol

### ISSUE THREAD

**Issue by suptimq** [JonasSchult/Mask3D#172]
Hi, I am wondering if anyone has any ideas for the below issue?

```python
>>> import MinkowskiEngine as ME
/home/tq422/Mask3D/third_party/MinkowskiEngine/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tq422/Mask3D/third_party/MinkowskiEngine/MinkowskiEngine/__init__.py", line 53, in <module>
    from MinkowskiEngineBackend._C import (
ImportError: /home/tq422/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/MinkowskiEngine-0.5.4-py3.10-linux-x86_64.egg/MinkowskiEngineBackend/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN9minkowski8cpu_gemmIdEEv12CBLAS_LAYOUT15CBLAS_TRANSPOSES2_iiiT_PKS3_S5_S3_PS3_
```

### Conda Env

```
conda list
# packages in environment at /home/tq422/anaconda3/envs/mask3d_cuda113:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    anaconda
_openmp_mutex             5.1                       1_gnu    anaconda
absl-py                   1.4.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albumentations            1.2.1                    pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
black                     21.4b2                   pypi_0    pypi
blas                      1.0                    openblas    anaconda
boltons                   23.0.0          py310h06a4308_0    anaconda
brotlipy                  0.7.0           py310h7f8727e_1002    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
ca-certificates           2024.7.2             h06a4308_0    anaconda
cachetools                5.3.0                    pypi_0    pypi
certifi                   2024.7.4        py310h06a4308_0    anaconda
cffi                      1.15.1          py310h5eee18b_3    anaconda
charset-normalizer        2.0.4              pyhd3eb1b0_0    anaconda
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
comm                      0.1.3                    pypi_0    pypi
conda                     23.3.1          py310h06a4308_0    anaconda
conda-content-trust       0.1.3           py310h06a4308_0    anaconda
conda-package-handling    2.0.2           py310h06a4308_0    anaconda
conda-package-streaming   0.7.0           py310h06a4308_0    anaconda
configargparse            1.5.3                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cryptography              39.0.1          py310h9ce1e76_0    anaconda
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.37                  pypi_0    pypi
dash                      2.9.3                    pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
debugpy                   1.6.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
detectron2                0.6                      pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastapi                   0.95.1                   pypi_0    pypi
fastjsonschema            2.16.3                   pypi_0    pypi
fire                      0.4.0                    pypi_0    pypi
flake8                    6.0.0                    pypi_0    pypi
flask                     2.2.3                    pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.4.0                 pypi_0    pypi
fvcore                    0.1.5.post20220512          pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
google-auth               2.17.3                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.54.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hydra-core                1.0.5                    pypi_0    pypi
idna                      3.4             py310h06a4308_0    anaconda
imageio                   2.21.1                   pypi_0    pypi
importlib-metadata        3.10.1                   pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
ipykernel                 6.22.0                   pypi_0    pypi
ipython                   8.12.0                   pypi_0    pypi
ipywidgets                8.0.6                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonpatch                 1.32               pyhd3eb1b0_0    anaconda
jsonpointer               2.1                pyhd3eb1b0_0    anaconda
jsonschema                4.17.3                   pypi_0    pypi
jupyter-client            8.2.0                    pypi_0    pypi
jupyter-core              5.3.0                    pypi_0    pypi
jupyterlab-widgets        3.0.7                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lazy-loader               0.2                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    anaconda
libffi                    3.4.2                h6a678d5_6    anaconda
libgcc-ng                 11.2.0               h1234567_1    anaconda
libgfortran-ng            11.2.0               h00389a5_1    anaconda
libgfortran5              11.2.0               h1234567_1    anaconda
libgomp                   11.2.0               h1234567_1    anaconda
libopenblas               0.3.21               h043d6bf_0    anaconda
libstdcxx-ng              11.2.0               h1234567_1    anaconda
libuuid                   1.41.5               h5eee18b_0    anaconda
loguru                    0.6.0                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
minkowskiengine           0.5.4                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
natsort                   8.3.1                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    anaconda
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
ninja                     1.10.2.3                 pypi_0    pypi
nomkl                     3.0                           0    anaconda
numpy                     1.24.2                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.0.6                    pypi_0    pypi
open3d                    0.17.0                   pypi_0    pypi
openblas-devel            0.3.21               h06a4308_0    anaconda
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0    anaconda
packaging                 23.0            py310h06a4308_0    anaconda
pandas                    2.0.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.11.1                   pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.1                     pypi_0    pypi
platformdirs              3.2.0                    pypi_0    pypi
plotly                    5.14.1                   pypi_0    pypi
pluggy                    1.0.0           py310h06a4308_1    anaconda
plyfile                   0.7.4                    pypi_0    pypi
portalocker               2.7.0                    pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  4.22.3                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycocotools               2.0.4                    pypi_0    pypi
pycodestyle               2.10.0                   pypi_0    pypi
pycosat                   0.6.4           py310h5eee18b_0    anaconda
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pydantic                  1.10.7                   pypi_0    pypi
pydeprecate               0.3.2                    pypi_0    pypi
pyflakes                  3.0.1                    pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyopenssl                 23.0.0          py310h06a4308_0    anaconda
pyparsing                 3.0.9                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0    anaconda
python                    3.10.9               h7a1cb2a_0    anaconda
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             0.20.0                   pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyviz3d                   0.2.28                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     25.0.2                   pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    anaconda
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.1          py310h06a4308_1    anaconda
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel.yaml               0.17.21         py310h5eee18b_0    anaconda
ruamel.yaml.clib          0.2.6           py310h5eee18b_1    anaconda
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.0                    pypi_0    pypi
sentry-sdk                1.20.0                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.6.3          py310h06a4308_0    anaconda
six                       1.16.0             pyhd3eb1b0_1    anaconda
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    anaconda
stack-data                0.6.2                    pypi_0    pypi
starlette                 0.26.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
tensorboard               2.12.2                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2023.4.12                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    anaconda
toml                      0.10.2                   pypi_0    pypi
toolz                     0.12.0          py310h06a4308_0    anaconda
torch                     1.12.1+cu113             pypi_0    pypi
torch-scatter             2.1.2                    pypi_0    pypi
torchvision               0.13.1+cu113             pypi_0    pypi
tornado                   6.3                      pypi_0    pypi
tqdm                      4.65.0          py310h2f386ee_0    anaconda
traitlets                 5.9.0                    pypi_0    pypi
trimesh                   3.14.0                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.15         py310h06a4308_0    anaconda
uvicorn                   0.21.1                   pypi_0    pypi
volumentations            0.1.8                    pypi_0    pypi
wandb                     0.15.0                   pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    anaconda
widgetsnbextension        4.0.7                    pypi_0    pypi
xz                        5.2.10               h5eee18b_1    anaconda
yacs                      0.1.8                    pypi_0    pypi
yarl                      1.8.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    anaconda
zstandard                 0.19.0          py310h5eee18b_0    anaconda
```

**Comment by LDP626** [comment]
I experienced the same issue when executing "bash /home/lz23/model_code/Mask3D-main/scripts/stpls3d/stpls3d_val.sh".

**Comment by liuhuayuan233** [comment]
same

**Comment by Yuehongzhe** [comment]
same
