### ISSUE TITLE
How to train from srcatch?

### ISSUE THREAD

**Issue by Bingoang** [JonasSchult/Mask3D#36]
Hi, JonasSchult!
I really appreciate your excellent work！When I ran the training code (scannet200), I met some problems:

Restoring states from the checkpoint path at saved/scannet200_benchmark/last-epoch.ckpt
Traceback (most recent call last):
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/ang/Mask3D-main/main_instance_segmentation.py", line 97, in main
    train(cfg)
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/ang/Mask3D-main/main_instance_segmentation.py", line 78, in train
    runner.fit(model)
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1067, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 182, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 343, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/ang/anaconda3/envs/mask3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for InstanceSegmentation:
        Missing key(s) in state_dict: "criterion.empty_weight". 

I've tried many ways but I cannot still solve it. Could you tell me How to train from scratch?
Thanks in advance!

**Comment by JonasSchult** [comment]
Hi!

Can you send me the script you executed to start the training?

Here, the script tries to load a previous checkpoint
`Restoring states from the checkpoint path at saved/scannet200_benchmark/last-epoch.ckpt`
Does this path exist?

Best,
Jonas

**Comment by Bingoang** [comment]
@JonasSchult
Thanks very much for your reply!
I downloaded your trained checkpoint and changed its name to "last-epoch.ckpt", and then put it into "saved/scannet200_benchmark/last-epoch.ckpt". Then, I ran the script:
`python main_instance_segmentation.py \
general.experiment_name="scannet200_benchmark" \
general.project_name="scannet200" \
data/datasets=scannet200 \
general.num_targets=201 \
data.num_labels=200 \
general.eval_on_segments=true \
general.train_on_segments=true \
data.train_mode=train_validation`
And it reported the problem I described in the issue. 

Now I found out that my  operations  above are wrong. After I removed the "scannet200_benchmark" folder and ran the the script, it can finally train from scratch~

**Comment by JonasSchult** [comment]
Hi Bingoang,

thanks for sharing your insights! Your first try failed because I provided checkpoints without optimizer state, i.e., the checkpoint does not contain the current epoch, learning rate, ... . I did this to make the checkpoints as small as possible. With additional information, they have been 3x as big and harder to download. In case you want to fine-tune such a provided checkpoint, you need to provide it with `general.checkpoint=PATH_TO_CKPT.ckpt` similar to [here](https://github.com/JonasSchult/Mask3D/blob/main/scripts/s3dis/s3dis_pretrained.sh#L17).

Best,
Jonas

**Comment by Bingoang** [comment]
@JonasSchult 
Thanks very much! Looking forward to more works of yours!
