### ISSUE TITLE
omegaconf.errors.ConfigKeyError: str interpolation key 'data.add_raw_coordinates' not found

### ISSUE THREAD

**Issue by TobyZhouWei** [JonasSchult/Mask3D#77]
Hi, I run "bash stpls3d_benchmark.sh" to test on stpls3d, and in config_base_instance_segmentation.yaml, I have changed conf like these

defaults:
  - data: outdoor
  - data/data_loaders: simple_loader
  - data/datasets: stpls3d

From the error,  'data.add_raw_coordinates' does seem not necessary for outdoor.yaml, but it doesn't work. How can I do to test on stpls3d.

Traceback (most recent call last):
  File "/root/Mask3D-main/main_instance_segmentation.py", line 99, in main
    test(cfg)
  File "/root/miniconda3/envs/mask3d/lib/python3.9/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/root/Mask3D-main/main_instance_segmentation.py", line 85, in test
    cfg, model, loggers = get_parameters(cfg)
  File "/root/Mask3D-main/main_instance_segmentation.py", line 48, in get_parameters
    flatten_dict(OmegaConf.to_container(cfg, resolve=True))
omegaconf.errors.ConfigKeyError: str interpolation key 'data.add_raw_coordinates' not found.

**Comment by JonasSchult** [comment]
Hi! :)
You only need to run this script [here](https://github.com/JonasSchult/Mask3D/blob/main/scripts/stpls3d/stpls3d_val.sh#L27).
No change to data to `outdoor` or smth else is needed :)

Best,
Jonas
