### ISSUE TITLE
TypeError: string indices must be integers in s3dis

### ISSUE THREAD

**Issue by hj2532006916** [JonasSchult/Mask3D#91]
![image](https://github.com/JonasSchult/Mask3D/assets/133661066/8fa3fbe0-601d-4988-8a24-7d4c7bc9c2f6)
if you know how to solve,please tell me!Thanks a lot

**Comment by JonasSchult** [comment]
Hi! :)

You can correct the S3DIS dataset like [this](https://github.com/JonasSchult/Mask3D/issues/8).

Best,
Jonas

**Comment by hj2532006916** [comment]
But I don't have the same problem as you，I don t know how to modify

**Comment by JonasSchult** [comment]
Can you send the full error message? :)

**Comment by PandaDalin** [comment]
2025-07-07 12:25:34.614 | INFO     | datasets.preprocessing.base_preprocessing:preprocess:47 - Tasks for Area_6: 47
[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   5 out of  47 | elapsed:    1.4s remaining:   12.1s
[Parallel(n_jobs=64)]: Done  10 out of  47 | elapsed:    1.8s remaining:    6.8s
[Parallel(n_jobs=64)]: Done  15 out of  47 | elapsed:    2.0s remaining:    4.4s
[Parallel(n_jobs=64)]: Done  20 out of  47 | elapsed:    2.1s remaining:    2.8s
[Parallel(n_jobs=64)]: Done  25 out of  47 | elapsed:    2.3s remaining:    2.0s
[Parallel(n_jobs=64)]: Done  30 out of  47 | elapsed:    2.6s remaining:    1.5s
[Parallel(n_jobs=64)]: Done  35 out of  47 | elapsed:    2.7s remaining:    0.9s
[Parallel(n_jobs=64)]: Done  40 out of  47 | elapsed:    2.8s remaining:    0.5s
[Parallel(n_jobs=64)]: Done  45 out of  47 | elapsed:    4.3s remaining:    0.2s
[Parallel(n_jobs=64)]: Done  47 out of  47 | elapsed:    7.3s finished
2025-07-07 12:25:44.249 | ERROR    | fire.core:_CallAndUpdateTrace:684 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (3306830), thread 'MainThread' (126894374393664):
Traceback (most recent call last):

  File "/home/lihongda/anaconda3/envs/mask3d_cuda113/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'datasets.preprocessing', '__loader__': <_frozen_importlib_external....
           │         └ <code object <module> at 0x7368e5907100, file "/home/lihongda/3D/Mask3D/datasets/preprocessing/s3dis_preprocessing.py", line 1>
           └ <function _run_code at 0x7368e5911bd0>
  File "/home/lihongda/anaconda3/envs/mask3d_cuda113/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'datasets.preprocessing', '__loader__': <_frozen_importlib_external....
         └ <code object <module> at 0x7368e5907100, file "/home/lihongda/3D/Mask3D/datasets/preprocessing/s3dis_preprocessing.py", line 1>

  File "/home/lihongda/3D/Mask3D/datasets/preprocessing/s3dis_preprocessing.py", line 282, in <module>
    Fire(S3DISPreprocessing)
    │    └ <class '__main__.S3DISPreprocessing'>
    └ <function Fire at 0x7368e27ba710>

  File "/home/lihongda/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 's3dis_preprocessing.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(verbose=False, interactive=False, separator='-', completion=None, help=False, trace=False)
                      │     │          └ ['preprocess', '--data_dir=/home/lihongda/3D/SoftGroup/dataset/s3dis/Stanford3dDataset_v1.2/', '--save_dir=data/processed/s3d...
                      │     └ <class '__main__.S3DISPreprocessing'>
                      └ <function _Fire at 0x7368e0f65480>
  File "/home/lihongda/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7368e0f655a0>
    └ <bound method BasePreprocessing.preprocess of <__main__.S3DISPreprocessing object at 0x7368b992fe50>>
> File "/home/lihongda/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ []
                └ <bound method BasePreprocessing.preprocess of <__main__.S3DISPreprocessing object at 0x7368b992fe50>>

  File "/home/lihongda/3D/Mask3D/datasets/preprocessing/base_preprocessing.py", line 57, in preprocess
    self.compute_color_mean_std(
    │    └ <function S3DISPreprocessing.compute_color_mean_std at 0x7368b99236d0>
    └ <__main__.S3DISPreprocessing object at 0x7368b992fe50>

  File "/home/lihongda/3D/Mask3D/datasets/preprocessing/s3dis_preprocessing.py", line 206, in compute_color_mean_std
    color_std.append(sample["color_std"])
    │         │      └ 'mean'
    │         └ <method 'append' of 'list' objects>
    └ []

TypeError: string indices must be integers
