### ISSUE TITLE
Traing scannet200 dataset error

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#96]
When I use these commands as 'python main_instance_segmentation.py \
general.experiment_name="scannet200_val" \
general.project_name="scannet200" \
data/datasets=scannet200 \
general.num_targets=201 \
data.num_labels=200 \
general.eval_on_segments=true \
general.train_on_segments=true'

The error occurs. Below is the traceback:
Traceback (most recent call last):
  File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py", line 106, in main
    train(cfg)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py", line 85, in train 
    runner.fit(model)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in f
it
    self._call_and_handle_interrupt(
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _
call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _
fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in 
_run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1065, in 
_restore_modules_and_callbacks
    self._checkpoint_connector.resume_start(checkpoint_path)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_conne
ctor.py", line 85, in resume_start
    self._loaded_checkpoint = self._load_and_validate_checkpoint(checkpoint_path)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_conne
ctor.py", line 89, in _load_and_validate_checkpoint
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 339, 
in load_checkpoint
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/plugins/io/torch_plugin.py", line 8
3, in load_checkpoint
    raise FileNotFoundError(f"Checkpoint at {path} not found. Aborting training.")
FileNotFoundError: Checkpoint at saved/scannet200_val/last-epoch.ckpt not found. Aborting training.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Any ideas to fix it? Thanks in advance!!!

**Comment by xiaotiancai899** [comment]
@francisengelmann @JonasSchult @eltociear

**Comment by JonasSchult** [comment]
Hi!

If you already created an experiment with the same name, the codebase tries to resume it from the latest checkpoint. In your case, it cannot find such a checkpoint.
> FileNotFoundError: Checkpoint at saved/scannet200_val/last-epoch.ckpt not found. Aborting training.

You can either delete the current experiment in the `saved/` folder or rename it `general.experiment_name="NEW_NAME"`.

Best,
Jonas

**Comment by xiaotiancai899** [comment]
> Hi!
> 
> If you already created an experiment with the same name, the codebase tries to resume it from the latest checkpoint. In your case, it cannot find such a checkpoint.
> 
> > FileNotFoundError: Checkpoint at saved/scannet200_val/last-epoch.ckpt not found. Aborting training.
> 
> You can either delete the current experiment in the `saved/` folder or rename it `general.experiment_name="NEW_NAME"`.
> 
> Best, Jonas

Hi, I followed your guidance, but another error occurs.

Traceback (most recent call last):
  File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py", line 106, in main
    train(cfg)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py", line 85, in train
    runner.fit(model)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1149, in _run
    self.strategy.setup(self)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/strategies/single_device.py", line 74, in setup
    super().setup(trainer)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 153, in setup
    self.setup_optimizers(trainer)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 141, in setup_optimizers
    self.optimizers, self.lr_scheduler_configs, self.optimizer_frequencies = _init_optimizers_and_lr_schedulers(
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 194, in _init_optimizers_and_lr_schedulers
    _validate_scheduler_api(lr_scheduler_configs, model)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 351, in _validate_scheduler_api
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `OneCycleLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic 
if you are using a custom LR scheduler.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by JonasSchult** [comment]
Hi! :)

Thanks for your interest in our work!

we have just released a [fix](https://github.com/JonasSchult/Mask3D/commit/9f25bf357c97ed7b80402a6233eee8d940c64aeb) which most likely will solve your issue. Just pull the latest version of the project and recreate your virtual python environment following the instructions [here](https://github.com/JonasSchult/Mask3D#dependencies-memo).

Previously, the issue occurred because we did not lock the packages in the Python environment to specific versions. We now made sure that the packages in the environment remain the same.

I will close the issue now. Please feel free to reopen it again if you continue to experience issues.

Best,
Jonas
