### ISSUE TITLE
MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory

### ISSUE THREAD

**Issue by bh-cai** [JonasSchult/Mask3D#98]
Thanks for you project at first. And then ,when I  run "python main_instance_segmentation.py
general.experiment_name="train1_scannet200_benchmark"
general.project_name="scannet200"
data/datasets=scannet200
general.num_targets=201
data.num_labels=200
general.eval_on_segments=true
general.train_on_segments=true
data.train_mode=train_validation"
to train on the sannet200,I got the run flows:
Epoch 14:  67%|██████   | 203/303 [10:42<05:16,  3.17s/it, loss=235, v_num=mark]Traceback (most recent call last):
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/mylabs/Mask3D/main_instance_segmentation.py", line 108, in main
    train(cfg)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/home/mylabs/Mask3D/main_instance_segmentation.py", line 84, in train
    runner.fit(model)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in _run_train
    self.fit_loop.run()
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 270, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 203, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 87, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 201, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 248, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 358, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1552, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1673, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 216, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 153, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/optim/adamw.py", line 119, in step
    loss = closure()
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 138, in _wrap_closure
    closure_result = closure()
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 146, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 132, in closure
    step_output = self._step_fn()
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 407, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 358, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/mylabs/Mask3D/trainer/trainer.py", line 151, in training_step
    output = self.forward(
  File "/home/mylabs/Mask3D/trainer/trainer.py", line 120, in forward
    x = self.model(
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mylabs/Mask3D/models/mask3d.py", line 237, in forward
    pcd_features, aux = self.backbone(x)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mylabs/Mask3D/models/res16unet.py", line 307, in forward
    out = self.block8(out)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mylabs/Mask3D/models/modules/resnet_block.py", line 55, in forward
    out = self.conv1(x)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/MinkowskiEngine-0.5.4-py3.10-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 314, in forward
    outfeat = self.conv.apply(
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/MinkowskiEngine-0.5.4-py3.10-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 72, in forward
    return fw_fn(
MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mylabs/Mask3D/main_instance_segmentation.py", line 114, in <module>
    main()
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/root/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 267, in run_and_report
    print_exception(etype=None, value=ex, tb=final_tb)  # type: ignore
TypeError: print_exception() got an unexpected keyword argument 'etype'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 
wandb: Run history:
wandb:                epoch ▁▁▁▁▁▁▂▂▂▃▃▃▃▃▃▃▃▄▄▅▅▅▅▅▅▅▅▅▆▆▇▇▇▇▇▇▇▇██
wandb:             lr-AdamW ▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▆▆▆▇▇▇██
wandb:        train_loss_ce █▇▇▇▆▅▆▅▅▄▆▅▆▄▄▃▆▅▃▅▁▄▅▃▃▃▅▄▂▃▃▂▅▃▅▄▄▁▄▂
wandb:      train_loss_ce_0 ▅▇▅▅▇▅▇▆▅█▆▃▇▅▅▃▅▄▇▅█▄▆▂▃▅▄▃▃▃▁▂▂▃▃▃▂▁▁▂
wandb:      train_loss_ce_1 ██▇▇▆▅▆▅▅▄▅▄▆▄▅▄▅▅▃▄▁▄▄▃▃▃▅▃▂▃▃▂▄▃▄▃▃▁▃▂
wandb:     train_loss_ce_10 █▇▆▆▅▅▆▄▅▄▆▅▅▄▅▃▅▅▃▅▁▄▅▃▃▃▅▄▃▃▃▃▅▃▅▄▄▂▄▃
wandb:     train_loss_ce_11 █▆▆▆▅▅▆▄▅▄▆▄▅▄▄▃▅▅▃▅▁▄▅▃▃▃▅▄▃▃▃▃▅▃▅▄▄▁▄▂
wandb:      train_loss_ce_2 █▇▇▆▆▅▆▄▅▄▆▄▅▄▅▃▅▅▃▅▁▄▄▃▃▃▅▄▃▃▃▃▅▃▄▄▄▂▃▂
wandb:      train_loss_ce_3 █▇▆▆▅▅▆▄▅▄▆▄▅▄▄▃▅▅▃▅▁▄▅▃▃▃▅▄▃▃▃▃▅▃▄▄▄▂▃▂
wandb:      train_loss_ce_4 █▇▆▆▅▅▆▄▅▄▆▄▅▄▄▃▅▅▃▅▁▄▅▃▃▃▅▄▃▃▃▃▅▃▄▄▄▁▃▂
wandb:      train_loss_ce_5 █▇▆▆▅▄▆▄▄▄▅▄▅▄▄▃▅▅▃▅▁▄▄▃▃▃▅▄▃▃▃▃▅▃▄▄▄▁▄▂
wandb:      train_loss_ce_6 █▇▆▆▅▅▆▄▄▄▆▅▅▄▄▃▅▅▃▅▁▄▅▃▃▃▅▄▃▃▃▃▅▃▄▄▄▂▃▃
wandb:      train_loss_ce_7 █▇▆▆▅▄▆▄▅▄▆▄▅▄▄▃▅▅▃▅▁▄▅▃▃▃▅▄▃▃▃▃▅▃▅▄▄▁▃▂
wandb:      train_loss_ce_8 █▇▇▇▅▅▆▅▅▄▆▅▆▄▄▃▆▅▃▅▁▄▅▃▃▃▅▄▃▃▃▃▅▃▅▄▄▁▄▂
wandb:      train_loss_ce_9 █▇▇▆▆▅▆▄▄▄▆▄▅▄▅▃▅▅▃▅▁▄▅▃▃▃▅▄▃▃▃▃▅▃▄▄▄▁▄▂
wandb:      train_loss_dice ▇██▇█▇██▇▇▇▆▇▅▆▅▄▅▄▄▆▄▅▅▅▄▄▄▃▄▄▃▂▃▁▃▂▂▃▂
wandb:    train_loss_dice_0 ▄▇▄▃▄▃▇▆▄▅▅▁▄▂▆▃▆█▆▆▇▆▆▄▃▅▇▆▄▆▅▄▅▆▄▇▄▃▇▇
wandb:    train_loss_dice_1 ▇██▇▇▇█▇▇▇▇▇▆▅▆▅▄▅▄▃▆▄▅▅▅▄▄▄▄▄▄▃▂▃▁▃▂▂▃▂
wandb:   train_loss_dice_10 ███▇█▇██▇▇▆▅▆▅▆▅▄▅▄▄▆▄▅▅▅▄▄▄▃▄▄▃▂▃▁▃▁▂▃▂
wandb:   train_loss_dice_11 ▇██▇█▇██▇▇▆▅▇▅▆▅▄▅▄▄▆▄▅▅▅▄▄▄▃▄▄▃▂▃▁▃▂▂▃▂
wandb:    train_loss_dice_2 ▇██▇█▇██▇▇▇▇▆▅▆▅▄▆▄▄▆▄▅▅▅▄▄▄▄▄▄▃▃▃▁▄▂▂▃▂
wandb:    train_loss_dice_3 ▇██▇█▇██▇▇▇▇▆▅▆▅▄▅▄▄▆▄▅▅▅▄▄▄▄▄▄▃▂▃▁▄▁▂▃▂
wandb:    train_loss_dice_4 ███▇█▇████▇▇▇▆▆▆▅▆▄▄▆▄▅▅▅▄▄▄▄▄▄▃▃▃▁▄▂▂▃▂
wandb:    train_loss_dice_5 ███▇█▇██▇▇▇▆▆▅▆▅▄▅▃▃▆▄▅▅▅▄▄▄▄▄▃▃▂▃▁▃▁▂▃▂
wandb:    train_loss_dice_6 ▇██▇█▇██▇▇▆▅▆▅▆▅▄▅▃▃▆▄▅▅▅▄▃▄▃▄▃▃▂▃▁▃▁▁▃▂
wandb:    train_loss_dice_7 ▇██▇█▇▇▇▇▇▆▆▆▅▆▅▄▅▃▃▆▄▅▄▅▃▃▃▃▃▃▂▂▃▁▃▁▁▃▂
wandb:    train_loss_dice_8 ▇██▇█▇██▇▇▇▆▇▅▆▅▄▆▄▄▆▄▅▄▅▄▃▄▃▄▄▃▂▃▁▃▁▂▃▂
wandb:    train_loss_dice_9 ▇██▇█▇██▇▇▆▅▆▅▆▅▄▅▃▄▆▄▅▅▅▄▄▄▃▄▄▃▂▃▁▃▁▂▃▂
wandb:      train_loss_mask ▇▃▇▇▇▇▃▄▆▅▄█▆▇▃▆▃▂▂▃▃▃▃▇▆▄▂▃▄▂▄▃▂▂▅▁▃▆▂▃
wandb:    train_loss_mask_0 █▇▇▇▆▅▅▅▅▄▄▄▄▃▃▃▂▂▃▂▂▂▁▂▂▂▂▁▂▁▁▁▁▁▂▁▁▂▁▁
wandb:    train_loss_mask_1 █▃▃▄▃▃▂▂▃▃▂▄▃▄▂▃▂▁▂▂▂▂▂▃▃▂▁▂▂▂▂▂▁▂▃▁▂▃▁▂
wandb:   train_loss_mask_10 ▇▃▇▇▇▇▃▄▆▅▄█▆▇▃▇▃▂▃▃▃▃▃▇▆▄▂▃▄▂▄▃▂▂▅▁▃▇▂▃
wandb:   train_loss_mask_11 ▇▄▇▇▇▇▃▄▆▄▄█▆▇▃▆▃▂▃▃▃▃▃▇▆▄▂▃▄▂▄▃▂▂▅▁▃▆▂▃
wandb:    train_loss_mask_2 █▃▅▅▅▅▃▃▅▄▄▇▄▅▃▅▂▂▂▂▂▃▂▅▅▃▂▃▃▂▃▃▂▂▄▁▂▅▂▂
wandb:    train_loss_mask_3 ▆▃▅▆▆▆▃▃▅▄▄█▅▆▃▅▂▂▂▃▃▃▂▆▅▃▂▃▄▂▃▃▂▂▄▁▂▆▂▃
wandb:    train_loss_mask_4 ▆▃▆▇▆▆▃▃▅▄▄█▅▆▃▆▂▂▂▃▃▃▂▆▅▃▂▃▄▂▃▃▂▂▄▁▂▆▂▂
wandb:    train_loss_mask_5 ▇▃▇▇▇▇▃▄▆▅▄█▆▇▃▆▃▂▃▃▃▃▃▇▆▄▂▄▄▂▄▃▂▃▅▁▃▆▂▃
wandb:    train_loss_mask_6 ▇▄▇▇▇▇▃▄▆▅▄█▆▇▃▆▃▂▂▃▃▃▃▇▆▄▂▃▄▂▄▃▂▂▅▁▃▆▂▂
wandb:    train_loss_mask_7 ▆▄▆▇▇▇▃▄▆▄▄█▆▇▃▆▃▂▃▃▃▃▃▇▆▄▂▃▄▂▄▃▂▃▅▁▃▆▂▃
wandb:    train_loss_mask_8 ▆▃▆▇▇▇▃▄▆▄▄█▆▇▃▆▂▂▂▃▃▃▂▆▆▄▂▃▄▂▃▃▂▂▅▁▃▆▂▂
wandb:    train_loss_mask_9 ▆▃▆▇▇▇▃▄▆▄▄█▆▇▃▆▃▂▃▃▃▃▃▇▆▄▂▃▄▂▄▃▂▂▅▁▃▆▂▂
wandb:      train_loss_mean █▆▅▄▄▃▃▃▂▂▂▁▁▁
wandb:   train_mean_loss_ce █▇▆▆▅▅▆▄▅▄▆▄▅▄▄▃▅▅▃▅▁▄▅▃▃▃▅▄▃▃▃▃▅▃▄▄▄▁▄▂
wandb: train_mean_loss_dice ▇██▇█▇██▇▇▇▆▆▅▆▅▄▅▄▄▆▄▅▅▅▄▄▄▃▄▄▃▂▃▁▃▁▂▃▂
wandb: train_mean_loss_mask █▅▇▇▆▆▄▄▅▄▄▇▅▅▃▅▃▂▃▃▃▃▂▅▄▃▂▃▃▂▃▂▂▂▄▁▂▅▂▂
wandb:  trainer/global_step ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇███
wandb: 
wandb: Run summary:
wandb:                epoch 14
wandb:             lr-AdamW 1e-05
wandb:        train_loss_ce 6.61817
wandb:      train_loss_ce_0 10.56585
wandb:      train_loss_ce_1 7.04124
wandb:     train_loss_ce_10 6.78035
wandb:     train_loss_ce_11 6.66567
wandb:      train_loss_ce_2 6.79488
wandb:      train_loss_ce_3 6.70028
wandb:      train_loss_ce_4 6.60369
wandb:      train_loss_ce_5 6.84299
wandb:      train_loss_ce_6 6.64393
wandb:      train_loss_ce_7 6.64156
wandb:      train_loss_ce_8 6.55064
wandb:      train_loss_ce_9 6.79635
wandb:      train_loss_dice 8.16914
wandb:    train_loss_dice_0 9.6263
wandb:    train_loss_dice_1 8.10693
wandb:   train_loss_dice_10 8.13096
wandb:   train_loss_dice_11 8.15024
wandb:    train_loss_dice_2 8.14323
wandb:    train_loss_dice_3 8.18708
wandb:    train_loss_dice_4 8.14605
wandb:    train_loss_dice_5 8.13217
wandb:    train_loss_dice_6 8.0971
wandb:    train_loss_dice_7 8.15064
wandb:    train_loss_dice_8 8.14192
wandb:    train_loss_dice_9 8.12903
wandb:      train_loss_mask 2.19819
wandb:    train_loss_mask_0 3.30113
wandb:    train_loss_mask_1 2.28254
wandb:   train_loss_mask_10 2.1731
wandb:   train_loss_mask_11 2.21837
wandb:    train_loss_mask_2 2.22903
wandb:    train_loss_mask_3 2.24881
wandb:    train_loss_mask_4 2.21069
wandb:    train_loss_mask_5 2.24276
wandb:    train_loss_mask_6 2.12589
wandb:    train_loss_mask_7 2.1558
wandb:    train_loss_mask_8 2.12202
wandb:    train_loss_mask_9 2.17425
wandb:      train_loss_mean 237.04103
wandb:   train_mean_loss_ce 7.01889
wandb: train_mean_loss_dice 8.25468
wandb: train_mean_loss_mask 2.28328
wandb:  trainer/global_step 4399
wandb: 
wandb: 🚀 View run train1_scannet200_benchmark at: https://wandb.ai/manjusaka_labs/scannet200/runs/train1_scannet200_benchmark
wandb: Synced 3 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: saved/train1_scannet200_benchmark/wandb/run-20230603_195259-train1_scannet200_benchmark/logs

so,I want to decrease bath_size,but I don't known where to do it ,and if I can decrease bath_size,the results would be affect?

And ,if I use more GPU to train, can I solved this problem? if it useful, can tell me where I can change in the code of the mask3D project. thank you very much,hope to hear you!

**Comment by JonasSchult** [comment]
You can overwrite standard parameters like this:

```
python main_instance_segmentation.py \
general.experiment_name="train1_scannet200_benchmark_new_exp" \
general.project_name="scannet200" \
data/datasets=scannet200 \
general.num_targets=201 \
data.num_labels=200 \
general.eval_on_segments=true \
general.train_on_segments=true \
data.train_mode=train_validation \
data.voxel_size=SET_TO_YOUR_DESIRED_VOXEL_SIZE \
data.batch_size=SET_TO_YOUR_DESIRED_BATCH_SIZE
```

The code is untested for different voxel sizes and batch sizes. Just try it out if you achieve satisfactory results :)

Best,
Jonas

**Comment by bh-cai** [comment]
Thank very much! best wish for you!
