### ISSUE TITLE
Traing scannet200 dataset error

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#99]
When I use these commands as 'python main_instance_segmentation.py
general.experiment_name="scannet200"
general.project_name="scannet200"
data/datasets=scannet200
general.num_targets=201
data.num_labels=200
general.eval_on_segments=true
general.train_on_segments=true'

An error occurs.

Traceback (most recent call last):
File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py", line 106, in main
train(cfg)
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
return task_function(cfg_passthrough)
File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py", line 85, in train
runner.fit(model)
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
self._call_and_handle_interrupt(
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
return trainer_fn(*args, **kwargs)
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
results = self._run(model, ckpt_path=self.ckpt_path)
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1149, in _run
self.strategy.setup(self)
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/strategies/single_device.py", line 74, in setup
super().setup(trainer)
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 153, in setup
self.setup_optimizers(trainer)
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 141, in setup_optimizers
self.optimizers, self.lr_scheduler_configs, self.optimizer_frequencies = _init_optimizers_and_lr_schedulers(
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 194, in _init_optimizers_and_lr_schedulers
_validate_scheduler_api(lr_scheduler_configs, model)
File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 351, in _validate_scheduler_api
raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler OneCycleLR doesn't follow PyTorch's LRScheduler API. You should override the LightningModule.lr_scheduler_step hook with your own logic
if you are using a custom LR scheduler.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Any ideas about this? Thanks in advance!!!!!!!!!

**Comment by xiaotiancai899** [comment]
@JonasSchult
